### ISSUE TITLE
Do not allow two rollups to share a table

### ISSUE THREAD

**Issue by mredivo** [jeffpierce/cassabon#82]
Rollup data for a path is written to a table whose name is determined form the retention period. This means that for any rollup definition such as the following, no two entries can have exactly the same retention period:

```
rollups:
    default:
        retention:
            - 6s:6h
            - 1m:7d
            - 1h:30d  <<< This goes into the 30-day table
            - 6h:30d  <<< So does this, rendering the data useless
            - 6h:365d
        aggregation: average
```

Proposed solution: Flag a warning when loading the configuration, and drop the definition (as we do for other such errors).
